- name: DEMO on filters
  hosts: localhost
  vars:
   NAME: sai krishna
   website: https://www.joindevops.com/batch-74s
   praposing: I love you all, guys
  tasks:
  - name: convert into upper case
    debug:
     msg: "Hello {{ NAME | upper}}"

  - name: convert into upper case
    debug:
     msg: "Hello {{ NAME | lower}}"

  - name: printing undefined variable
    debug:
     msg: "{{ COURSE | default('devops') }}"

  - name: extarct hostname
    debug:
     msg: "{{ website | urlsplit('hostname') }}"

  - name: split
    debug:
     msg: "{{ praposing | split(',') }}"
